name: base_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.7
  go_router: ^9.0.3
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  u_credit_card: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
